# Generated by Django 5.1.7 on 2025-03-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('electronics', 'کالای دیجیتال'), ('clothing', 'پوشاک'), ('books', 'کتاب و لوازم تحریر'), ('home_appliances', 'لوازم خانگی'), ('beauty', 'آرایشی و بهداشتی'), ('toys', 'اسباب\u200cبازی و کودک'), ('sports', 'ورزشی و سفر'), ('food', 'خواروبار'), ('automotive', 'خودرو و موتور'), ('jewelry', 'زیورآلات و اکسسوری'), ('furniture', 'مبلمان و دکوراسیون'), ('medical', 'تجهیزات پزشکی'), ('music', 'موسیقی و آلات موسیقی'), ('others', 'چیز های دیگر')], default='electronics', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
