# Generated by Django 5.1.7 on 2025-03-17 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('electronics', 'کالای دیجیتال'), ('clothing', 'پوشاک'), ('books', 'کتاب و لوازم تحریر'), ('home_appliances', 'لوازم خانگی'), ('beauty', 'آرایشی و بهداشتی'), ('toys', 'اسباب\u200cبازی و کودک'), ('sports', 'ورزشی و سفر'), ('food', 'خواروبار'), ('automotive', 'خودرو و موتور'), ('jewelry', 'زیورآلات و اکسسوری'), ('furniture', 'مبلمان و دکوراسیون'), ('medical', 'تجهیزات پزشکی'), ('music', 'موسیقی و آلات موسیقی'), ('others', 'چیز های دیگر')], default='electronics', max_length=20)),
                ('price', models.PositiveIntegerField(default=0)),
                ('offer', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('offer_price', models.PositiveIntegerField(blank=True, null=True)),
                ('inventory', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(max_length=500, upload_to='None/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='market_imag_created_7c03a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='market.product')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='comments_created_5a6deb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='market.product')),
            ],
            options={
                'db_table': 'product_info',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='product_inf_created_6d58c3_idx')],
            },
        ),
    ]
