# Generated by Django 5.1.7 on 2025-03-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_product_inventory_product_offer_product_offer_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
