# Generated by Django 5.1.7 on 2025-03-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_productinfo_text_alter_productinfo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='None/'),
        ),
    ]
