# Generated by Django 5.1.7 on 2025-07-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold_count',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
