# Generated by Django 5.1.7 on 2025-07-12 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_product_sold_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='starts',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='به این محصول از یک تا پنج امتیاز دهید', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
