# Generated by Django 5.1.7 on 2025-07-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_image_image_file_alter_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
