# Generated by Django 5.1.7 on 2025-10-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_amazingoffers'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
