# Generated by Django 5.1.7 on 2025-07-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
