# Generated by Django 5.1.7 on 2025-07-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.TextField(choices=[('awaiting_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('shipping', 'در حال ارسال'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده'), ('returned', 'مرجوع شده')], default='awaiting_payment'),
        ),
    ]
